# elasticsearch config parameters
elasticsearch:
    host: "http://localhost"
    port: "9200"
    thread: 6

# ontology for step 0: data ingestion
ingestion:
    # in staging version. Data is using Matteo's extracted data in 222 machine. 
    input.folder: "mobile_net"

# parameter for step 1: track infected person
track.person:
    # this is the running parameter of all the 
    person.type: "patient.higor" # which subset we choose 
    day.before: 15 # track days before infected
    day.after: 15  # track days after infected

# parameter for step 2: check close contact
track.close_contact:
    distance.minimum: "8m"
    minute.before: 10
    minute.after: 10

# ===========  List the pipline file of every patient resources ================

patient.higor:
    input.file: "patient_input/list_of_infected.csv"
    folders:  
        track: "patient_track"                # step1 output
        close_contact: "close_contact"   # step2 output
        result: "result"    # result folder