index.ingested:
- fortaleza_03_01
- fortaleza_03_02
- fortaleza_03_03
- fortaleza_03_04
- fortaleza_03_05
- fortaleza_03_06
- fortaleza_03_07
- fortaleza_03_08
- fortaleza_03_09
- fortaleza_03_10
- fortaleza_03_11
- fortaleza_03_12
- fortaleza_03_13
- fortaleza_03_14
- fortaleza_03_15
- fortaleza_03_16
- fortaleza_03_17
- fortaleza_03_18
- fortaleza_03_19
- fortaleza_03_20
- fortaleza_03_21
- fortaleza_03_22
- fortaleza_03_23
- fortaleza_03_24
- fortaleza_03_25
- fortaleza_03_26
- fortaleza_03_27
- fortaleza_03_28
- fortaleza_03_29
- fortaleza_03_30
- fortaleza_03_31
