# elasticsearch config parameters
elasticsearch:
    host: "http://localhost"
    port: "9200"
    thread: 6

# ontology for step 0: data ingestion
ingestion:
    # in staging version. Data is using Matteo's extracted data in 222 machine. 
    input.folder: "mobile_net"

# parameter for step 1: track infected person
track.person:
    patient.higor:
        input: "patient_input/list_of_infected.csv"
        output.folder: "patient_track"
        day.before: 15
        day.after: 15
    # Add other field of person you want to track here:
    # type of person : 
    #    field1 : value1
    #    field2 : value2
    #    ....

# parameter for step 2: check close contact
track.close_contact:
    patient.higor:
        input.folder: "patient_track"
        output.folder: "close_contact"
        distance: "10m"
        minute.before:  2
        minute.after: 2
