# elasticsearch config parameters
elasticsearch:
    host: "http://localhost"
    port: "9200"
    thread: 12
    
# ontology for step 0: data ingestion
ingestion:
    # in staging version. Data is using Matteo's extracted data in 222 machine. 
    input.folder: 
        app: "/Users/shaojun/Projects/COVID19/mobile_net_app"
        grandata: "/Users/shaojun/Projects/COVID19/mobile_net_grandata"

# parameter for step 1: track infected person
track.person:
    # this is the running parameter of all the 
    person.type: "patients" # which subset we choose 
    day.before: 14 # track days before infected
    day.after: 14  # track days after infected
    timezone: 'America/Fortaleza'
    num.cores: 12

# parameter for step 2: check close contact
track.contact:
    distance.max: 8
    minute.before: 0
    minute.after: 15
    timezone: 'America/Fortaleza'
    num.cores: 11

# parameter for contact model
contact.model:
    rho: 0.14

# ===========  List the pipline file of every patient resources ================

patients:
    input.file: "/Users/shaojun/Projects/COVID19/patient_input/infected_list.csv"
    folders:  
        track: "/Users/shaojun/Projects/COVID19/patient_track"            # step 2 output of patient track
        contact: "/Users/shaojun/Projects/COVID19/close_contact"          # step 3.1 output patient to all contact
        contact.profile:  "/Users/shaojun/Projects/COVID19/contact_profile" # step 3.2 output shorten contact profiles
        track.contact: "/Users/shaojun/Projects/COVID19/contact_track"    # step 4 generate contacts
        deliver: "/Users/shaojun/Projects/COVID19/deliver"                # step 5 generate deliver result