# ontology of elasticsearch
# this is the basic ontology for all output
# DO NOT change it
elasticsearch:
  id: "mobileId"
  source: "dataSource"
  time: "acquisitionTime"
  location: "location"
  moving_rate: "movingRate"

# input ontology map for ingestion
ingestion:
  app:
    id: "mobileId"
    time: "acquisitionTime"
    latitude: "lat"
    longitude: "long"
  grandata:
    id: "id"
    time: "datastamp"
    latitude: "lat"
    longitude: "long"

# input ontology map for tracking person
track.person:
  patients:
    time: 'sympton_date'
    id: "mobile_ID"
    status: "status" 
    flag.dead: "OBITO"
    time.dead: "date_obito"
    timezone: 'America/Fortaleza'
  
  # this is for the standard template for 1st layer file
  # DO NOT change
  1st_layer:
    time: 'sourceTime'
    id: 'targetId'          
    source: 'targetDataSrc' 
    timezone: 'America/Fortaleza'

  # this is for research
  levels:
    time: 'sourceTime'
    id: 'targetId'          # do not change          
    source: 'targetDataSrc' # do not change
    status: "status" 
    flag.dead: "OBITO"
    time.dead: "date_obito"
    timezone: 'America/Fortaleza'