# ontology of elasticsearch
# this is the basic ontology for all output
# DO NOT change it
elasticsearch:
  id: "mobileId"
  time: "acquisitionTime"
  location: "location"
  moving_rate: "movingRate"

# input ontology map for ingestion
ingestion:
  app:
    id: "id"
    time: "datastamp"
    latitude: "lat"
    longitude: "long"
  grandata:
    id: "id"
    time: "datastamp"
    latitude: "lat"
    longitude: "long"

# input ontology map for tracking person
track.person:
  patients:
    date: 'date'
    id: "Mobile_id"
    status: "dead" 
    flag.dead: "OBITO"
    timezone: 'America/Fortaleza'
    
  1st_layer:
    date: 'infectedTime'
    id: 'targetId'
    timezone: 'America/Fortaleza'