# ontology of elasticsearch
# this is the basic ontology for all output
# DO NOT change it
elasticsearch:
  id: "mobileId"
  source: "dataSource"
  time: "acquisitionTime"
  location: "location"
  moving_rate: "movingRate"

# input ontology map for ingestion
ingestion:
  app:
    id: "mobileId"
    time: "acquisitionTime"
    latitude: "lat"
    longitude: "long"
  grandata:
    id: "id"
    time: "datastamp"
    latitude: "lat"
    longitude: "long"

# input ontology map for tracking person
track.person:
  patients:
    time: 'date'
    id: "mobileId"
    status: "status" 
    flag.dead: "OBITO"
    timezone: 'America/Fortaleza'
    
  1st_layer:
    time: 'earliestContactTime'
    id: 'targetId'          # do not change
    source: 'targetDataSrc' # do not change
    timezone: 'America/Fortaleza'