index.ingested:
- fortaleza_03_01
- fortaleza_03_02
- fortaleza_03_03
- fortaleza_03_04
- fortaleza_03_05
- fortaleza_03_06
- fortaleza_03_07
- fortaleza_03_08
- fortaleza_03_09
- fortaleza_03_10
- fortaleza_03_11
- fortaleza_03_12
- fortaleza_03_13
- fortaleza_03_14
- fortaleza_03_15
- fortaleza_03_16
- fortaleza_03_17
- fortaleza_03_18
- fortaleza_03_19
- fortaleza_03_20
- fortaleza_03_21
- fortaleza_03_22
- fortaleza_03_23
- fortaleza_03_24
- fortaleza_03_25
- fortaleza_03_26
- fortaleza_03_27
- fortaleza_03_28
- fortaleza_03_29
- fortaleza_03_30
- fortaleza_03_31
- fortaleza_04_01
- fortaleza_04_02
- fortaleza_04_03
- fortaleza_04_04
- fortaleza_04_05
- fortaleza_04_06
- fortaleza_04_07
- fortaleza_04_08
- fortaleza_04_09
- fortaleza_04_10
- fortaleza_04_11
- fortaleza_04_12
- fortaleza_04_13
- fortaleza_04_14
- fortaleza_04_15
- fortaleza_04_16
- fortaleza_04_17
- fortaleza_04_18
- fortaleza_04_19
- fortaleza_04_20
- fortaleza_04_21
- fortaleza_04_22
- fortaleza_04_23
- fortaleza_04_24
- fortaleza_04_25
- fortaleza_04_26
- fortaleza_04_27
- fortaleza_04_28
- fortaleza_04_29
- fortaleza_04_30
- fortaleza_05_01
- fortaleza_05_02
- fortaleza_05_03
- fortaleza_05_04
- fortaleza_05_05
- fortaleza_05_06
- fortaleza_05_07
- fortaleza_05_08
- fortaleza_05_09
